"""Seventhrevision

Revision ID: 70691e379b2b
Revises: 2a908045617f
Create Date: 2023-04-30 17:41:52.593295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70691e379b2b'
down_revision = '2a908045617f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
